#!/bin/sh /etc/rc.common
#
# Copyright (c) 2018 [n/a] info@embeddora.com All rights reserved
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#        * Redistributions of source code must retain the above copyright
#          notice, this list of conditions and the following disclaimer.
#        * Redistributions in binary form must reproduce the above copyright
#          notice, this list of conditions and the following disclaimer in the
#          documentation and/or other materials provided with the distribution.
#        * Neither the name of The Linux Foundation nor
#          the names of its contributors may be used to endorse or promote
#          products derived from this software without specific prior written
#          permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON-INFRINGEMENT ARE DISCLAIMED.    IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Abstract: server-side self-termination daemon

# The later the better; in the rest no restrictions - callback organization on client siide admits launch at any _time
START=99

# The later the better; but seems like nothing meaningful can be done on in stop()
STOP=99

# Address of <br-lan> (in general case, in particular cases - different)
AUX_SRV_ADDR="192.168.0.1"

# Can be anything except "80" (which is already occupied)
AUX_SRV_PORT="88"

# Part of HTTP-request causing immediate reboot of DUT/CPE
BADWORD="suicide"


TRACE_OUT="/var/.uhttpd.$AUX_SRV_PORT.strace.out"

start()
{
	# This is to avoid warning from <cat>, because <strace> in detached shell produces it not right away
	touch $TRACE_OUT

	# Launch aux. HTTP-server in detached shell
	strace -o $TRACE_OUT  -e trace=network -s9999 -eread /usr/sbin/uhttpd -p $AUX_SRV_PORT -f -h /www -r Touch P5 -x /cgi-bin &

	echo "Aux. HTTP-server started" > /dev/console

	# Initialize to guarantee the following <while-do-done> starts with correct input data
	DEATH_PACKET=""

	# Check if some non-empty value was obtained on <eval-cat-grep>
	while [ -z "$DEATH_PACKET" ]
	do
		# Check if the deatch-packet has arived. No need to check AUX_SRV_ADDR:AUX_SRV_PORT - in <TRACE_OUT> they're all correct
		DEATH_PACKET=`eval cat $TRACE_OUT | grep "$BADWORD"`

	done	

	echo "Aux. HTTP-server has recived a death-packet. Self-terminating." > /dev/console

	# Reboot without executing stop-routines of </etc/rc.d/Kxxx> 
	reboot -f

	# Not reachable
}

stop()
{
	# This is to avoid warning of build-time syntax check
	:
}
